@startuml
hide empty description
title BufferPool 数据结构示意图

state 1 as "capacity:512" {
    state 1_1 as "512bytes"
    state 1_2 as "512bytes"
    1_1->1_2
}
state 2 as "capacity:256"{
 state 2_1 as "256 bytes"
 state 2_2 as "256 bytes"
 2_1->2_2
}
state 3 as "capacity:1024"{
 state 3_1 as "1024 bytes"
 state 3_2 as "1024 bytes"
 state 3_3 as "1024 bytes"
 3_1->3_2
 3_2->3_3
}

state 4 as "capacity:768"{
 state 4_1 as "768 bytes"
}

state 5 as "capacity:2048"{
 state 5_1 as "2048 bytes"
 state 5_2 as "2048 bytes"

 5_1->5_2
}

3-->5


1-->2
1-->3
3-->4

@enduml